import Head from "next/head";
import { Container, Main } from "../styles/sharedstyles";
import CryptoList from "../components/CryptoList/CryptoList";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <CryptoList />
      </Main>
    </Container>
  );
}
